William/scroll performance
cuappdev/eatery-ios pull request #199
Opened 2019-08-27 15:54 UTC by whoiswillma

- The search bar and filter bar are in their own section, instead of being added directly to the `collectionView`.
  * This was done to make the search and filter bar stop "jiggling" when scrolling the `collectionView`.
- The AppDev logo reached by pulling down on the `collectionView` is now instantiated in the `EateriesSharedViewController` to stop each `EateryViewController` from needing to add their own copy of it.

2019-08-27 16:11 UTC, young-k commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +
I don't think we should have `\n` after a comment, I don't think it adds any clarity!

2019-08-27 16:11 UTC, young-k commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        }
Can't this `for` loop and the above `for view in views` be combined?

2019-08-27 16:11 UTC, young-k commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        }
might be cleaner with a ternary, but this is personal preference –– will leave up to you!

2019-08-27 16:11 UTC, young-k commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +            // view is provided
Can't this comment fit in two lines // is there a reason for splitting it up?

2019-08-27 18:09 UTC, whoiswillma commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +            // view is provided
I use 80 columns as a soft guide, but I'm up for bumping that to 120

2019-08-27 18:16 UTC, whoiswillma commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        }
Certainly, but I think two for-loops reads better because they distinguish the setup from the animations.

2019-08-27 18:34 UTC, young-k commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +            // view is provided
cc @kevinchan159

2019-08-27 19:13 UTC, whoiswillma commented
I noticed an issue where entering search text would cause the keyboard to dismiss. Because `reloadData` was being called in the `reloadEateries` method, the search bar would be removed from the window and then reattached, causing it to lose its first responder status. 

Instead of trying to track which sections to insert and remove, I made the number of sections constant and just hide and show them as needed, which is simpler and also stops the search and filter bar cell from being reloaded

2019-08-27 21:06 UTC, kevinchan159 requested changes
looks great! just left some small nits

2019-08-27 21:06 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        for view in views {
nit: pref to use `forEach`

2019-08-27 21:06 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        for view in views {
same here

2019-08-27 21:06 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        }
i agree w/ young here. you could just add comments inside the for loop but if you feel strongly about this you can keep it

2019-08-27 21:06 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        }
pref ternary here too

2019-08-27 21:06 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        } else {
nit: could remove the `else` since you're returning on line 590

2019-08-27 21:06 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +            return gridLayout.sectionInset
same here

2019-08-27 21:06 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        } else {
same here

2019-08-27 21:08 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +            // view is provided
Lets go w/ 100 characters as the char limit per line. Thats the recommended limit in the Google/Airbnb style guides

2019-08-27 21:14 UTC, whoiswillma commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        for view in views {
Why in general is it preferable to use `forEach` over the regular `for` statements?

2019-08-27 21:25 UTC, whoiswillma commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        }
I don't feel particularly strong about this; It's more a case of it was that way before (which is not a good reason in-and-of-itself, but which I think is reasonable if I came to the code like it is) in combination with (what I perceive as) the additional readability.

It's more so that the `for`-loops behave as separate paragraphs in an essay: they serve different purposes, therefore they should be split, even if semantically having one and having two are the same.

2019-08-28 02:47 UTC, kevinchan159 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        for view in views {
There isnt really a benefit of using one over the other besides consistency. Since Swift is functional and we try to use functional functions like `map/filter/reduce` where possible, I think using `forEach` where possible makes sense

2019-08-28 02:48 UTC, kevinchan159 approved these changes
approving to unblock but address comments before merging pls!

2019-08-28 02:49 UTC, kevinchan159 commented
small note: Could you click on `Resolve conversation` after you finish addressing a comment? Just makes it a bit easier for reviewers to know what you've addressed

2019-08-28 04:38 UTC, chalo2000 commented on Eatery/Controllers/Eateries/EateriesCollectionViewGridLayout.swift
> +        if collectionView.traitCollection.horizontalSizeClass == .regular
Perhaps consider replacing this with a ternary

2019-08-28 05:01 UTC, chalo2000 reviewed
Just tiny fixes and a question about the sections in the collectionView

2019-08-28 05:01 UTC, chalo2000 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +            print("Updating \(type(of: self))", Date())
Remove print statement

2019-08-28 05:01 UTC, chalo2000 commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        return 4
Why are there 4 sections if our switch above only has cases for 3 sections and we return a 1 whenever section == 0  below? Something seems off to me with this.

2019-08-28 12:38 UTC, whoiswillma commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        for view in views {
I see three main reasons for sticking with "regular" `for` loops with Eatery:
1. Eatery already uses `for` almost everywhere, so being consistent is good (when it makes sense)
2. `forEach` produces `Void` as its value, whereas `map` (and the other functional methods in Swift) produce meaningful values. This matters because `for` loops are control flow statements, and should therefore be distinguished from expressions that produce values. Instead of having to read the words `forEach`, `for` loops are separated visually from the rest of the code, by the syntax itself as well as by syntax highlighting. 
3. `for` loops are generally used to manipulate state, whereas `map` is expected to _not_  manipulate state. Similarly to 2., as human beings who have to look at code with our eye-balls, having this separation is useful for distinguishing the purpose of code.

2019-08-28 12:43 UTC, whoiswillma commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +            print("Updating \(type(of: self))", Date())
Hmmn, I feel keeping this one is worthwhile. It doesn't get printed that often and it's also a pretty significant event.

2019-08-28 12:48 UTC, whoiswillma commented on Eatery/Controllers/Eateries/EateriesViewController.swift
> +        return 4
The search and filter bars are now a cell in the collection view. In order to make Some Things™ easier, I put them in their own section. Now there are four sections: the "bars" section which only ever contains one cell, and then the remaining three sections ("favorites", "open", and "closed") as usual.

2019-08-28 12:54 UTC, whoiswillma commented on Eatery/Controllers/Eateries/EateriesCollectionViewGridLayout.swift
> +        if collectionView.traitCollection.horizontalSizeClass == .regular
I think a ternary would be a bit too unwieldy: the conditional and both expressions are pretty long.

2019-08-28 15:13 UTC, chalo2000 approved these changes

2019-08-28 15:33 UTC, merged